### ISSUE TITLE
Needs to also copy the sorting layer

### ISSUE THREAD

**Issue by bsparks** [SoftBoiledGames/Parallaxer#2]
https://github.com/PixelSparkStudio/Parallaxer/blob/2cb5d99708a7c02cfeb84f7651081b95fb9931f0/Runtime/ParallaxExpansibleElement.cs#L211

`spriteRenderer.sortingLayerID = base.SpriteRenderer.sortingLayerID;` like that otherwise it stays on default

**Comment by savioti** [comment]
Good call, I've just updated the repo with your input.
